# Generated by Django 5.0.6 on 2024-05-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='laste_name',
            new_name='last_name',
        ),
    ]
