# Generated by Django 5.0.6 on 2024-05-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
