# Generated by Django 5.0.6 on 2024-05-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_laste_name_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
    ]
